.TH BIOMETRIC-DEVICE-DISCOVER 1

.SH NAME
biometric-device-discover \- Discover the device supported by biometric authentication services

.SH SYNOPSIS
.B biometric-device-discover
[\fBOPTION\fR]

.SH DESCRIPTION
.B biometric-device-discover
Discover the device supported by biometric authentication services in the current system.

.SH OPTIONS
.IP -t
device type ("serial", "usb", "pcie" or "all")
.IP -w
Write the discover results to configuration file (just for serial device)
.IP -h
Display help message and exit.
