.TH BIOMETRIC-CONFIG-TOOL 8

.SH NAME
biometric-config-tool \- Manage and configure biometric authentication services

.SH SYNOPSIS
.B biometric-config-tool
[\fBOPTION\fR]
.IR BuiltinCommands ...

.SH DESCRIPTION
.B biometric-config-tool
Manage and configure biometric authentication services.

.SH OPTIONS
.IP "-h,  --help"
Display help message and exit.

.SH BuiltinCommands
.IP add-driver
Add drivers, usage: biometric-config-tool add-driver [OPTION...] DriverName DriverFilePath
.RS
.IP OPTIONS:
.RS
.IP "-f, --force"
When there is a driver of the same name, force to override it
.IP "-d, --disable"
Only add driver and Not enable driver
.IP "-h, --help"
Display "biometric-config-tool add-driver" help message and exit.
.RE
.RE
.IP remove-driver
Remove drives, usage: biometric-config-tool remove-driver [OPTION...] Driver1 [Driver2 ...]
.RS
.IP OPTIONS:
.RS
.IP "-i, --ignore"
Ignore nonexistent drivers
.IP "-h, --help"
Display "biometric-config-tool remove-driver" help message and exit.
.RE
.RE
.IP enable-driver
Enable drivers, usage: biometric-config-tool enable-driver [OPTION...] Driver1 [Driver2 ...]
.RS
.IP OPTIONS:
.RS
.IP "-i, --ignore"
Ignore nonexistent drivers
.IP "-h, --help"
Display "biometric-config-tool enable-driver" help message and exit.
.RE
.RE
.IP disable-driver
Disable drivers, usage: biometric-config-tool disable-driver [OPTION...] Driver1 [Driver2 ...]
.RS
.IP OPTIONS:
.RS
.IP "-i, --ignore"
Ignore nonexistent drivers
.IP "-h, --help"
Display "biometric-config-tool disable-driver" help message and exit.
.RE
.RE
.IP set-key
Set the key value of the specified driver, usage: biometric-config-tool set-key [OPTION...] DriverName Key Value
.RS
.IP OPTIONS:
.RS
.IP "-h, --help"
Display "biometric-config-tool set-key" help message and exit.
.RE
.RE
.IP remove-key
remove the key value of the specified driver, usage: biometric-config-tool remove-key [OPTION...] DriverName Key
.RS
.IP OPTIONS:
.RS
.IP "-i, --ignore"
Ignore nonexistent drivers
.IP "-h, --help"
Display "biometric-config-tool remove-key" help message and exit.
.RE
.RE
